[package]
name = "iced_reg_tree"
version = "0.1.0"
authors = ["Radovan Bla≈æek <blazra@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { version = "0.13", features = ["advanced", "web-colors"] }
svd-parser = "0.14.6"
